config/routes.rb
Rails.application.routes.draw do


  root 'kintaib_pages#top'
  get '/signup', to:'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users do
    member do
      get 'works/edit', :param => 'date'
      get 'edit_work', to: 'users#edit_work'
    end
    resources :works
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_one_month, only:[:index, :edit, :update]
  

  before_action :admin_or_correct_user, only: [:index, :edit, :update, :show]
  
  def index
    @user = User.find(params[:user_id])
    @worked_sum = @user.attendances.where.not(started_at: nil).count
    
  end
  
  def create
    @user = User.find(params[:user_id])
    @attendance_save = @user.attendances.find_by(worked_on: Date.current)
    if @attendance_save.started_at.nil?
      if @attendance_save.update_attributes(user_id:params[:user_id], worked_on: Date.current, started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます"
        redirect_to user_works_path @user
      else
        flash[:danger] = "出勤開始 登録に失敗しました。やり直してください。"
        render :index
      end
    elsif @attendance_save.finished_at.nil?
      if @attendance_save.update_attributes(user_id:params[:user_id], finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした"
        redirect_to user_works_path @user
      else
        flash[:danger] = "退勤 登録に失敗しました。やり直してください。"
        render :index
      end
    end
  end
  
  def show
    @user = User.find(params[:user_id])
    
  end
  
  def edit
    @user = User.find(params[:user_id])
    @first_day = params[:id].to_date
    @attendance_update ||= Attendance.new
  end
  
  def update
  begin
    @attendances ||= Attendance.new
    ActiveRecord::Base.transaction do
      
      attendances_params.each do |id, item|
        @attendance_update = Attendance.find(id)
        
        @attendance_update.attributes = (item)

        @attendance_update.save!(context: :hoge)
      end
    end
    flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
    redirect_to edit_user_work_path(@user.id) and return
  rescue ActiveRecord::RecordInvalid
    
    flash.now[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    render :edit
  end
  end
  
  
  private
  
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
    
    
    def admin_or_correct_user
      @user = User.find(params[:id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "編集権限がありません。"
        redirect_to(root_url)
      end
    end
  
end

app/helpers/works_helper.rb
module WorksHelper
  
  def zaisha(finish, start)
    finish = finish.floor_to(15.minute)
    start = start.floor_to(15.minute)
    format("%.2f", (((finish - start) / 60) / 60))
  end
  
  



end

app/views/works/edit.html.erb
<h1>編集画面</h1>

   <%= render 'shared/error_messages', :object => @attendance_update %>


<table class="table table-bordered table-striped" id="table-attendances">
  <thead>
    <tr>
      <th rowspan="1">日付</th>
      <th rowspan="1">曜日</th>
      <th colspan="1">出社</th>
      <th colspan="1">退社</th>
      <th rowspan="1">在社時間</th>
      <th rowspan="1">備考</th>
      <th rowspan="1">残業指示</th>
      <th rowspan="1">指示者</th>
    </tr>

  </thead>
  
  <tbody>

<%= form_with(model: @user, url: user_work_path(@user.id, date: @first_day), local: true, method: :patch) do |f| %>

  <% @attendances.each do |day| %>
  <%= f.fields_for "attendances[]", day do |attendance| %>
    <tr>
      <td><%= l(day.worked_on, format: :short) %></td>
      <td class="<%="wday#{day.worked_on.wday}"%>"><%= $days_of_the_week[day.worked_on.wday] %></td>
      <% l(day.started_at, format: :hour ) if day.started_at.present? %>
      <% if (Date.current + 1 > day.worked_on) %>
        <td><%= attendance.time_field :started_at, class: "form-control" %></td>
        <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
        <td>
          <% if day.started_at.present? && day.finished_at.present? %>
            <%= zaisha(day.finished_at, day.started_at) %>
          <% end %>
        </td>
        <td><%= attendance.text_field :note %></td>
        <td>9</td>
        <td>9</td>
      <% else %>
        <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
        <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
        <td>
          <% if day.started_at.present? && day.finished_at.present? %>
            <%= zaisha(day.finished_at, day.started_at) %>
          <% end %>
        </td>
        <td><%= attendance.text_field :note %></td>
        <td>9</td>
        <td>9</td>
      <% end %>
    </tr>
    <% end %>
  <% end %>

  </tbody>

</table>

<div class="list-save-btn">
  <%= f.submit "まとめて更新", class: "btn btn-default btn-outline-secondary" %>
  <%= link_to "キャンセル", user_works_path(current_user.id, date: @first_day), class: "btn btn-default btn-outline-secondary" %>
</div>

<% end %>

app/views/works/index.html.erb
<table class="table table-bordered kintai-list" id="table-attendances-top">
	<tbody>
		<tr>
			<td><%= link_to "←", user_works_path(date: @first_day.prev_month), class: "btn btn-default btn-outline-secondary" %>
			<%= l(@first_day, format: :middle) %> 時間管理表
			<%= link_to "→", user_works_path(date: @first_day.next_month), class: "btn btn-default btn-outline-secondary" %>
			</td>
			<td class="mx-auto">指定勤務時間：<%= format_basic_info(@user.work_time) %></td>
			<td colspan="3">基本時間：<%= format_basic_info(@user.basic_time) %></td>
			<td>初日：<%= l(@first_day, format: :short) %></td>
		</tr>
		<tr>
			<td>所属：<%= @user.department %></td>
			<td>氏名：<%= @user.name %></td>
			<td>コード</td>
			<td></td>
			<td>出勤日数 <%= @worked_sum %></td>
			<td>締め <%= l(@last_day, format: :short) %></td>
		</tr>
	</tbody>
</table>


<%= button_to '勤怠を編集', edit_user_work_path(@user, @first_day),method: :get, class: "btn btn-default btn-outline-secondary"  %>


<table class="table table-bordered table-striped" id="table-attendances">
  <thead>
    <tr>
      <th rowspan="2">日付</th>
      <th rowspan="2">曜日</th>
      <th colspan="3">出社</th>
      <th colspan="3">退社</th>
      <th rowspan="2">在社時間</th>
      <th rowspan="2">備考</th>
      <th rowspan="2">残業指示</th>
      <th rowspan="2">指示者</th>
    </tr>
    <tr>
      <th>時</th><th>分</th><th>ボタン</th>
      <th>時</th><th>分</th><th>ボタン</th>
    </tr>
  </thead>
  

  <tbody>
    <% @sum = 0 %>
    <% @attendances.each do |day| %>
    <tr>
      
      <td><%= l(day.worked_on, format: :short) %></td>
      <td class="<%="wday#{day.worked_on.wday}"%>"><%= $days_of_the_week[day.worked_on.wday] %></td>
      
      <td><%= l(day.started_at.floor_to(15.minute), format: :hour ) if day.started_at.present? %></td>
      <td><%= l(day.started_at.floor_to(15.minute), format: :minut ) if day.started_at.present? %></td>
      <td> 
        <% if (Date.current == day.worked_on) && day.started_at.nil? %>
          <%= link_to "出勤登録", user_works_path(@user,Time.current), method: :post, class: "btn btn-default btn-outline-secondary" %>
        <% end %>
      </td>
      
      
      <td><%= l(day.finished_at.floor_to(15.minute), format: :hour) if day.finished_at.present? %></td>
      <td><%= l(day.finished_at.floor_to(15.minute), format: :minut) if day.finished_at.present? %></td>
      <td>
        <% if (Date.current == day.worked_on) && day.started_at.present? && day.finished_at.nil? %>
          <%= link_to "退勤登録", user_works_path(@user,Time.current), method: :post, class: "btn btn-default btn-outline-secondary" %>
        <% end %>
      </td>
      
      <td>
        <% if day.started_at.present? && day.finished_at.present? %>
          <%= @i = zaisha(day.finished_at, day.started_at).to_f %>
          <% @sum += @i %>
        <% end %>
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>

   
    <% end %>
    
    <tr>
      <th colspan="2"></th>
      <th colspan="6"></th>
      <th colspan="1">在社時間合計：<%= @sum %></th>
      <th colspan="1"></th>
      <th colspan="1"></th>
      <th colspan="1"></th>
    </tr>

    
    
    
    
  </tbody>

</table>

app/views/works/show.html.erb
<% provide(:title, @user.name) %>
<%= render 'shared/error_messages', object: @user %>
<table class="table table-bordered">
	<tbody>
		<tr>
			<td>----年-月 勤怠管理表</td>
			<td>指定勤務時間：<%= format_basic_info(@user.work_time) %></td>
			<td colspan="3">基本時間：<%= format_basic_info(@user.basic_time) %></td>
			<td>初日 -/-</td>
		</tr>
		<tr>
			<td>所属：<%= current_user.department %></td>
			<td>氏名：<%= current_user.name %></td>
			<td>コード</td>
			<td></td>
			<td>出勤日数 --</td>
			<td>締め -/-</td>
		</tr>
	</tbody>
</table>


<%= button_to '勤怠を編集', "#", class: "btn btn-default btn-info"  %>


<table class="table table-bordered table-striped" id="table-attendances">
  <thead>
    <tr>
      <th rowspan="2">日付</th>
      <th rowspan="2">曜日</th>
      <th colspan="3">出社</th>
      <th colspan="3">退社</th>
      <th rowspan="2">在社時間</th>
      <th rowspan="2">備考</th>
      <th rowspan="2">残業指示</th>
      <th rowspan="2">指示者</th>
    </tr>
    <tr>
      <th>時</th><th>分</th><th>ボタン</th>
      <th>時</th><th>分</th><th>ボタン</th>
    </tr>
  </thead>
  
  <tbody>
    <% (@first_day..@last_day).each do |day| %>
    <tr>
      <td><%= l(day, format: :short) %></td>
      
      <td><%= $days_of_the_week[day.wday] %></td>
      <td>8</td><td>9</td><td>8</td>
      <td>9</td><td>9</td><td>9</td>
      <td>9</td>
      <td>9</td>
      <td>9</td>
      <td>9</td>
    </tr>
    <% end %>
    

    
    
    
    
  </tbody>

</table>