config/routes.rb
Rails.application.routes.draw do


  root 'kintaib_pages#top'
  get '/signup', to:'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users do
    member do
      get 'works/edit', :param => 'date'
      get 'edit_work', to: 'users#edit_work'
    end
    resources :works
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :email, presence: true
  validates :name, presence: true

  
  has_secure_password
  
  validates :department, length: { in: 2..30 }, allow_blank: true
  
  
  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]

  before_action :admin_user, only: [:destroy, :index, :edit_work]
  before_action :admin_or_correct_user, only: [:show, :edit, :update]
  
  def index
    @users = User.paginate(page: params[:page]).search(params[:search])
    if params[:search]
      @title_search = "検索結果"
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = '新規登録に成功しました'
      redirect_to @user
    else
      flash[:danger] = '新規登録に失敗しました'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
    
  end
  
  def update
    @user = User.find(params[:id])
   
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render :edit
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to @user
    else
      render :index
    end
  end
  
  def edit_work
    @user = User.find(params[:id])
  end
  

    

    
  
  private
    
    def user_params
      params.require(:user).permit(:name, :email, :department, :basic_time, :work_time, :password, :password_confirmation)
    end
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  
    def admin_user
      redirect_to root_url unless current_user.admin?
    end

    def admin_or_correct_user
      @user = User.find(params[:id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "編集権限がありません。"
        redirect_to(root_url)
      end
    end
  

end

app/helpers/users_helper.rb
module UsersHelper
  def format_basic_info(time)
    format("%.2f", (( time.hour * 60 ) + time.min ) / 60.0 )
  end
end

app/views/users/edit.html.erb
<%= provide(:title, "Edit") %>

<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3" >
    <%= form_with(model: @user, local: true) do |form| %>
      <%= render 'shared/error_messages', :object => @user %>
      <%= form.label :name, class: 'label-user--edit' %>
      <%= form.text_field :name, class: 'form-control' %>
      
      <%= form.label :email, class: 'label-user--edit' %>
      <%= form.email_field :email, class: 'form-control' %>
      
      <%= form.label :department, "所属", class: "label-login" %>
      <%= form.text_field :department, class: 'form-control' %>


      <%= form.label :password, class: 'label-user--edit' %>
      <%= form.password_field :password, class: 'form-control' %>
      
      <%= form.label :password_confirmation, class: 'label-user--edit' %>
      <%= form.password_field :password_confirmation, class: 'form-control' %>
      
      <%= form.submit "変更を保存する", class: 'btn btn-primary btn-block btn-user--edit' %>
    
    <% end %>
  </div>
</div>

app/views/users/edit_work.html.erb
<%= provide(:title, "Edit") %>

<h1>基本情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3" >
    <%= form_with(model: @user, local: true) do |form| %>
    
      <%= form.label :work_time, "指定勤務時間", class: "label-login" %>
      <%= form.time_field :work_time, class: 'form-control' %>
      
      <%= form.label :basic_time, "基本時間", class: "label-login" %>
      <%= form.time_field :basic_time, class: 'form-control' %>
      
      <%= form.submit "変更を保存する", class: 'btn btn-primary btn-block btn-user--edit' %>
    
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "Users") %>
<h1>
<%= @title_search || '全てのユーザー' %></title>  


</h1>

<div class="col-md-10 col-md-offset-1">
  <%= form_tag(users_path, :method => "get") do %> 
  <div class="input-group">
    <%= text_field_tag :search, params[:search], placeholder: "キーワード検索", class: "form-control" %>
    <span class="input-group-btn">
      <%= submit_tag "検索", :name => nil, class: "btn btn-primary" %>
    </span>
  </div>
  <% end %>
</div>


<div class="row">

  <div class="col-md-10 col-md-offset-1">
    <%= will_paginate @users, :previous_label => '前へ', :next_label => '次へ' %>
    <table class="table table-condensed table-hover" id="table-users">

      <tbody>
        <% @users.each do |user| %>
        <tr>
            
              
            <% if user.admin? %>
              <td id="none-border">
            <% else %>
              <td>
            <% end %>
            <p class="user-list-height">
              
              
              
            <% if user.admin? %>
              <%= link_to '管理者', user_works_path(user.id) %><font color="silver"> | </font>
            <% else %>
              <%= link_to user.name, user_works_path(user.id) %><font color="silver"> | </font>
            <% end %>
            
            
            <%= link_to '勤怠情報編集', edit_work_user_path(user.id) %><font color="silver">
            <% if user.admin? %>
            <% else %>
               | </font><%= link_to '削除', user_path(user), method: :delete %>
            <% end %></td>
            </p>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @users, :previous_label => '前へ', :next_label => '次へ' %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>ユーザー登録</h1>
<p>このページでは必要な項目を入力して、ユーザーを新規作成します。</p>
<%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name, "名前", class: "label-login" %>
    <%= f.text_field :name, class: 'form-control' %>
    
    <%= f.label :email, "Eメール", class: "label-login" %>
    <%= f.email_field :email, class: 'form-control' %>
    
    <%= f.label :department, "所属", class: "label-login" %>
    <%= f.text_field :department, class: 'form-control' %>
    
    <%= f.label :password, "パスワード", class: "label-login" %>
    <%= f.password_field :password, class: 'form-control' %>
    
    <%= f.label :password_confirmation, "パスワード", class: "label-login" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    
    <%= f.submit class: 'btn btn-primary btn-block btn-user--edit' %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, 'ユーザー詳細') %>

<h1>ユーザー詳細</h1>

<table class="table table-bordered">
  <tr>
    <th class="active">名前</th><td><%= @user.name %></td>
  </tr>
  <tr>
    <th class="active">Eメール</th><td><%= @user.email %></td>
  </tr>
  <tr>
    <th class="active">所属</th><td><%= @user.department %></td>
  </tr>
  
  <tr>
    <th class="active">指定勤務時間</th><td><%= l(@user.work_time, format: :time) %></td>
  </tr>
  
  <tr>
    <th class="active">基本時間</th><td><%= l(@user.basic_time, format: :time) %></td>
  </tr>
</table>