config/routes.rb
Rails.application.routes.draw do


  root 'kintaib_pages#top'
  get '/signup', to:'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users do
    member do
      get 'works/edit', :param => 'date'
      get 'edit_work', to: 'users#edit_work'
    end
    resources :works
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="footer">
<hr>
  <div class="footer-left">
    The Ruby on Rails Tutorial by Michael Hartl
  </div>



  <div class="footer-right">
    <ul>
      <li>About</li>
      <li>Contact</li>
      <li>News</li>
    </ul>
  </div>


</div>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <% if logged_in? %>
          <%= link_to "勤怠システム", user_works_path(current_user), id: "logo" %>
        <% else %>
          <%= link_to "勤怠システム", root_path, id: "logo" %>
        <% end %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to "トップへ", user_works_path(current_user) %></li>
            <% else %>
              <li><%= link_to "トップへ", root_path %></li>
            <% end %>
             
            <% if logged_in? && current_user.admin? %>
              <li><%= link_to "ユーザー一覧", users_path %></li>
            <% end %>
        <% if logged_in? && current_user.admin? %> 
          <li><%= link_to "基本情報の修正", user_works_path(current_user) %></li>
        <% end %>    
        <% if logged_in? %>
        
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザー詳細", current_user %></li>
              <li><%= link_to "アカウント情報の更新", edit_user_path(current_user.id) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "ログイン", login_path %></li>
          <% end %>
          
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= render 'layouts/shim' %>
    

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>

    <footer>
    <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>